'use client';
import {useEffect,useState} from 'react';
import {Volume2,Music2,Sparkles,Check,RotateCcw,ChevronRight,Layers} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogAction} from './ui/alert-dialog';
import {Switch} from './ui/switch';
import {Tabs,TabsList,TabsTrigger,TabsContent} from './ui/tabs';
import {CardView,MapView,Rune} from './game-ui';
import {CARDS,KEYWORDS,RELICS} from '@/lib/game-data';
import type {Action,GameState,OwnedCard} from '@/lib/game-engine';
import {music,sfx} from '@/lib/game-audio';
const titles:Record<string,string>={deck:'你的牌组',draw:'抽牌堆',discard:'弃牌堆',exhaust:'消耗堆',help:'冒险指南',settings:'旅途设置',map:'尖塔地图',log:'战斗记录',relics:'随行遗物',upgrade:'淬炼一张卡牌',remove:'遗忘一张卡牌'};
type Props={s:GameState;modal:string|null;close:()=>void;act:(a:Action)=>void;sound:boolean;setSound:(v:boolean)=>void;bgm:boolean;setBgm:(v:boolean)=>void;motion:boolean;setMotion:(v:boolean)=>void;reduced:boolean;saved:boolean;restart:boolean;setRestart:(v:boolean)=>void;newRun:()=>void};
export function GameDialogs({s,modal,close,act,sound,setSound,bgm,setBgm,motion,setMotion,reduced,saved,restart,setRestart,newRun}:Props){
 const [filter,setFilter]=useState('all'),[inspect,setInspect]=useState<OwnedCard|null>(null);
 useEffect(()=>{setFilter('all');setInspect(null);},[modal]);
 const pile=modal==='draw'?[...s.combat.draw].sort((a,b)=>a.id.localeCompare(b.id)):modal==='discard'?s.combat.discard:modal==='exhaust'?s.combat.exhaust:s.deck;
 const filtered=pile.filter(x=>(filter==='all'||CARDS[x.id].type===filter)&&(modal!=='upgrade'||(!x.up&&x.id!=='curse')));
 const choose=(owned:OwnedCard)=>{if(modal==='upgrade'){act({type:'upgrade',uid:owned.uid});close();}else if(modal==='remove'){act({type:'buy',item:'remove',uid:owned.uid});close();}else setInspect(owned);};
 const isCards=['deck','draw','discard','exhaust','upgrade','remove'].includes(modal??'');
 return <><Dialog open={modal!==null} onOpenChange={v=>{if(!v)close();}}><DialogContent className={['game-dialog',isCards||modal==='map'?'wide-dialog':'',modal==='map'?'map-dialog':''].join(' ')}><DialogTitle>{modal?titles[modal]:''}{['deck','draw','discard','exhaust'].includes(modal??'')&&<small> {pile.length} 张</small>}</DialogTitle>
 {modal==='help'&&<><DialogDescription>你是月之剑姬莉雅。穿过三幕、24 层尖塔，用卡牌与月辉击败蚀月神姬。</DialogDescription><div className="help-steps">{[['观察意图','敌人头顶显示下一次行动。剑刃是攻击，盾牌是防御。'],['打出卡牌','每回合恢复 3 能量、抽 5 张牌。攻击牌需要选择敌人，技能通常直接生效。'],['积累与释放','用弦月斩、凝月积累月辉，再用月华一闪打出爆发。月辉可跨回合保留。'],['选择你的路','战后选牌。地图上选择相连节点，营火恢复或升级，商店完善构筑，精英掉落遗物。']].map(([title,text],i)=><div key={title}><span>0{i+1}</span><p><b>{title}</b>{text}</p></div>)}</div><div className="keyword-list">{KEYWORDS.map(([key,text])=><details key={key}><summary>{key}<ChevronRight size={15}/></summary><p>{text}</p></details>)}</div><div className="keyboard-guide"><span><kbd>1–9</kbd>选牌</span><span><kbd>E / Enter</kbd>结束回合</span><span><kbd>M</kbd>地图</span><span><kbd>D</kbd>牌组</span><span><kbd>Esc</kbd>取消</span></div></>}
 {modal==='settings'&&<><DialogDescription>月光下，按自己的节奏旅行。</DialogDescription><div className="settings-row"><span><Volume2 size={20}/><span>战斗音效<small>出牌、攻击与胜利提示</small></span></span><Switch checked={sound} onCheckedChange={v=>{setSound(v);if(v)sfx('click');}} aria-label="战斗音效"/></div><div className="settings-row"><span><Music2 size={20}/><span>月夜旋律<small>轻柔的原创程序合成音乐</small></span></span><Switch checked={bgm} onCheckedChange={v=>{setBgm(v);music(v);}} aria-label="背景音乐"/></div><div className="settings-row"><span><Sparkles size={20}/><span>动态效果<small>{reduced?'已遵循系统减少动态效果设置':'角色呼吸、粒子与战斗过渡'}</small></span></span><Switch checked={motion&&!reduced} disabled={reduced} onCheckedChange={setMotion} aria-label="动态效果"/></div><div className="save-note"><Check size={16}/>{saved?'进度自动保存在此浏览器，关闭页面后可继续。':'当前浏览器不允许保存进度，请保持页面开启。'}</div><button className="danger-button" onClick={()=>{close();setRestart(true);}}><RotateCcw size={17}/>重新开始冒险</button><p className="version-note">月蚀尖塔 · 原创卡牌冒险 · v1.0<br/>灵感来自《杀戮尖塔》 · 三幕 / 26 种卡牌 / 12 件遗物</p></>}
 {modal==='map'&&<><DialogDescription className="sr-only">查看尖塔路线，在地图阶段选择相连节点前进。</DialogDescription><MapView s={s} readOnly={s.phase!=='map'} onNode={n=>{act({type:'node',row:n.row,col:n.col});close();}}/></>}
 {modal==='relics'&&<><DialogDescription>你的旅途中，每一件遗物都留下了一点力量。</DialogDescription><div className="relic-collection">{s.relics.map(id=><div key={id}><Rune name={RELICS[id].icon} size={29}/><div><h3>{RELICS[id].name}</h3><p>{RELICS[id].desc}</p></div></div>)}</div></>}
 {modal==='log'&&<><DialogDescription>最近的旅途与战斗记录，最新的在最上方。</DialogDescription><ol className="combat-log">{s.log.map((line,i)=><li key={i}><span>{String(s.log.length-i).padStart(2,'0')}</span>{line}</li>)}</ol></>}
 {isCards&&<><DialogDescription>{modal==='upgrade'?'选择一张卡牌进行永久升级。下方卡牌展示升级后的效果。':modal==='remove'?'支付 60 金币，永久移除一张卡牌。可以移除诅咒以净化牌组。':modal==='draw'?'按牌名展示，不代表抽取顺序。抽牌堆为空时，弃牌堆会洗牌后成为新的抽牌堆。':modal==='exhaust'?'消耗的卡牌本场战斗不再抽到，下场战斗会回归。':'点击卡牌查看完整效果，随时回顾你的构筑。'}</DialogDescription><Tabs value={filter} onValueChange={v=>setFilter(String(v))} className="deck-tabs"><TabsList variant="line">{[['all','全部'],['attack','攻击'],['skill','技能'],['power','能力'],['curse','诅咒']].map(([value,label])=><TabsTrigger key={value} value={value}>{label}</TabsTrigger>)}</TabsList>{['all','attack','skill','power','curse'].map(value=><TabsContent key={value} value={value}><div className="deck-grid">{filtered.map(owned=><CardView key={owned.uid} owned={modal==='upgrade'?{...owned,up:true}:owned} onClick={()=>choose(owned)} preview compact/>)}</div>{filtered.length===0&&<div className="empty-pile"><Layers size={35}/><p>这里还没有卡牌。</p></div>}</TabsContent>)}</Tabs>{inspect&&<div className="card-inspection"><Rune name={CARDS[inspect.id].icon} size={28}/><div><h3>{CARDS[inspect.id].name}{inspect.up?'＋':''}</h3><p>{CARDS[inspect.id].text[inspect.up?1:0]}</p>{!inspect.up&&inspect.id!=='curse'&&<small>升级后：{CARDS[inspect.id].text[1]}</small>}</div></div>}</>}
 </DialogContent></Dialog>
 <AlertDialog open={restart} onOpenChange={setRestart}><AlertDialogContent className="game-dialog"><AlertDialogTitle>开启新的旅途？</AlertDialogTitle><AlertDialogDescription>当前的冒险进度会被替换。你将以初始牌组与完整生命，重新踏入遗忘庭院。</AlertDialogDescription><div className="confirm-actions"><AlertDialogCancel className="secondary-button">继续当前冒险</AlertDialogCancel><AlertDialogAction className="primary-button" onClick={newRun}>重新开始</AlertDialogAction></div></AlertDialogContent></AlertDialog></>;
}
