'use client';
import type { CSSProperties, ReactNode } from 'react';
import { Moon, Swords, Shield, Sparkles, Wind, Feather, Star, Zap, Heart, Flower2, Eye, Eclipse, Waves, Skull, Gem, Bell, Sun, Compass, Hourglass, Crown, Flame, ShoppingBag, HelpCircle, Gift, Check, LockKeyhole, ArrowUp } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { Progress } from '@/components/ui/progress';
import { CARDS, CHAPTERS, FOES, NODE_LABELS } from '@/lib/game-data';
import { reachable } from '@/lib/game-engine';
import { CARD_ART } from '@/lib/card-art';
import { RELIC_ART } from '@/lib/relic-art';
import { POTION_ART } from '@/lib/potion-art';
import type { GameState, MapNode, OwnedCard } from '@/lib/game-engine';

const icons={moon:Moon,swords:Swords,shield:Shield,sparkles:Sparkles,wind:Wind,feather:Feather,star:Star,zap:Zap,heart:Heart,flower:Flower2,eye:Eye,eclipse:Eclipse,waves:Waves,skull:Skull,gem:Gem,bell:Bell,sun:Sun,compass:Compass,hourglass:Hourglass,crown:Crown,combat:Swords,elite:Skull,camp:Flame,shop:ShoppingBag,event:HelpCircle,chest:Gift,boss:Crown};
export function Rune({name,size=20,...rest}:{name:string;size?:number;className?:string}){const Icon=icons[name as keyof typeof icons]??Sparkles;return <Icon size={size} strokeWidth={1.5} {...rest}/>;}
export function RelicIcon({id,size=40}:{id:string;size?:number}){const art=RELIC_ART[id];return <img className="relic-art" src={art.src} alt={art.alt} width={size} height={size} style={{'--relic-size':`${size}px`} as CSSProperties} decoding="async" draggable={false}/>;}
export function PotionIcon({id,size=40}:{id:string;size?:number}){const art=POTION_ART[id];return <img className="potion-art" src={art.src} alt={art.alt} width={size} height={size} style={{'--potion-size':`${size}px`} as CSSProperties} decoding="async" draggable={false}/>;}
export function Tip({title,text,children}:{title:string;text?:string;children:ReactNode}){return <Tooltip><TooltipTrigger className="tip-trigger" render={<span tabIndex={0}/>}>{children}</TooltipTrigger><TooltipContent className="game-tooltip"><strong>{title}</strong>{text&&<p>{text}</p>}</TooltipContent></Tooltip>;}
export function CardView({owned,onClick,disabled=false,selected=false,index,handSize=5,compact=false,preview=false}:{owned:OwnedCard;onClick?:()=>void;disabled?:boolean;selected?:boolean;index?:number;handSize?:number;compact?:boolean;preview?:boolean}){
 const d=CARDS[owned.id];const art=CARD_ART[owned.id];const u=owned.up?1:0;const angle=index===undefined?0:(index-(handSize-1)/2)*Math.min(4,20/handSize);
 return <button disabled={disabled} onClick={onClick} className={`game-card ${d.type} ${selected?'selected':''} ${owned.up?'upgraded':''} ${compact?'compact':''} ${preview?'preview-card':''}`} style={{'--angle':`${angle}deg`,'--lift':`${Math.abs(angle)*2.5}px`} as CSSProperties} aria-label={`${d.name}${owned.up?'升级':''}，${d.cost===99?'无法打出':d.cost+'能量'}，${d.text[u]}`}>
  <span className="card-cost">{d.cost===99?'×':d.cost}</span><div className="card-image"><img className="card-illustration" src={art.src} alt={art.alt} width={1536} height={1024} loading={index===undefined?'lazy':'eager'} decoding="async" draggable={false}/><Rune name={d.icon}/></div><div className="card-text"><h3>{d.name}{owned.up&&<sup>＋</sup>}</h3><small>{({attack:'攻击',skill:'技能',power:'能力',curse:'诅咒'})[d.type]} <span>·</span> {d.rarity}</small><p>{d.text[u].split(/(\d+)/).map((t,i)=>/^\d+$/.test(t)?<b key={i}>{t}</b>:t)}</p></div>{index!==undefined&&<span className="card-hotkey">{index+1}</span>}{owned.up&&<span className="upgrade-mark"><ArrowUp size={10}/></span>}
 </button>;
}
export function HealthBar({hp,max,enemy=false}:{hp:number;max:number;enemy?:boolean}){return <div className={`healthbar ${enemy?'enemy-health':''}`}><Progress value={hp} max={max} aria-label={enemy?'敌方生命':'生命'} className="hp-progress"/><span>{hp} / {max}</span></div>;}
export function MapView({s,onNode,readOnly=false}:{s:GameState;onNode:(n:MapNode)=>void;readOnly?:boolean}){
 const chapter=CHAPTERS[s.act];const x=(col:number)=>110+col*175;const y=(row:number)=>530-row*66;
 return <div className="map-view"><div className="map-story"><span className="eyebrow">CHAPTER {['I','II','III'][s.act]}</span><h2>{chapter.name}</h2><div className="title-rule">✧</div><p>{chapter.story}</p><div className="map-progress"><span>攀登进度</span><strong>{Math.max(1,s.act*8+s.floor+1).toString().padStart(2,'0')}<small> / 24</small></strong></div><p className="map-instruction">{readOnly?'完成当前遭遇后，即可继续前进。':'选择一条相连的路线。每一次选择，都在书写你的命运。'}</p><div className="map-legend">{['combat','elite','event','camp','shop','chest'].map(k=><span key={k}><Rune name={k} size={15}/>{NODE_LABELS[k]}</span>)}</div></div><div className="route-scroll"><div className="route-canvas"><svg viewBox="0 0 570 595" preserveAspectRatio="none" className="route-lines" aria-hidden="true">{s.map.slice(0,7).flatMap(row=>row.flatMap(n=>s.map[n.row+1].filter(next=>next.row===7||Math.abs(next.col-n.col)<=1).map(next=><path key={`${n.row}-${n.col}-${next.col}`} d={`M ${x(n.col)} ${y(n.row)} C ${x(n.col)} ${y(n.row)-35}, ${x(next.col)} ${y(next.row)+35}, ${x(next.col)} ${y(next.row)}`} className={n.visited&&next.visited?'traversed':n.visited&&next.row===s.floor+1?'upcoming':''}/>)))}</svg>{s.map.flat().map(n=>{const available=!readOnly&&reachable(s,n);const current=n.row===s.floor&&n.col===s.col;return <button key={`${n.row}-${n.col}`} className={`map-node ${n.kind} ${n.visited?'visited':''} ${available?'available':''} ${current?'current':''}`} style={{left:`${x(n.col)/5.7}%`,top:`${y(n.row)}px`}} disabled={!available} onClick={()=>onNode(n)} aria-label={`第 ${n.row+1} 层，${NODE_LABELS[n.kind]}${available?'，可前往':''}`}><span className="node-symbol">{n.visited&&!current?<Check size={19}/>:<Rune name={n.kind} size={n.kind==='boss'?31:23}/>}</span><small>{n.kind==='boss'?FOES[`boss${s.act}`].name.split(' · ')[0]:NODE_LABELS[n.kind]}</small>{current&&<span className="you-are-here">当前</span>}{available&&<span className="node-pulse"/>}</button>;})}<div className="route-start"><LockKeyhole size={14}/><span>入口已在身后</span></div></div></div></div>;
}
