'use client';
import { Coins, Check, ArrowRight, Heart, Flame, Swords, FlaskConical, Trash2, ChevronRight, Gift, Sparkles, Sunrise, Moon, RotateCcw, Layers } from 'lucide-react';
import { CardView, MapView, Rune, Tip } from './game-ui';
import { CARDS, RELICS } from '@/lib/game-data';
import { cardPrice } from '@/lib/game-engine';
import type { Action, GameState } from '@/lib/game-engine';
export const POTIONS:Record<string,{name:string;desc:string}>={heal:{name:'月露药剂',desc:'恢复 20 点生命，不消耗能量。'},energy:{name:'星火药剂',desc:'获得 2 点能量。'},fire:{name:'辉光药剂',desc:'对选中敌人造成 20 点直接伤害。默认目标为第一个存活敌人。'}};
const EVENTS=[
 {kicker:'THE SILVER SPRING',name:'记忆之泉',icon:'waves',text:'庭院深处，泉水倒映着一轮并不存在的月亮。水面传来轻轻的声音：“你想治愈伤口，还是成为更强大的自己？”',choices:[['饮下泉水','恢复 18 点生命。'],['献出一段记忆','失去 6 点生命，最大生命增加 8。']]},
 {kicker:'THE FORBIDDEN LIBRARY',name:'无字之书',icon:'sparkles',text:'一本没有文字的书，悬浮在落满灰尘的书架之间。翻开它的瞬间，你看见了自己从未学过的剑术，以及一个不属于你的梦。',choices:[['领悟剑意','随机升级 2 张牌。若已全部升级，恢复 8 点生命。'],['阅读最后一页','获得随机史诗牌与诅咒「旧日梦魇」。']]},
 {kicker:'THE WANDERING STRANGER',name:'月下赌局',icon:'compass',text:'戴着兜帽的旅人把一枚硬币抛向月亮。“四分之三的机会，换一个足以改变旅途的小东西。你愿意相信命运吗？”',choices:[['掷出硬币','支付 25 金币，75% 的概率获得随机遗物。'],['礼貌地告别','获得 12 金币。']]},
 {kicker:'THE FORGOTTEN ALTAR',name:'沉眠的祭坛',icon:'eclipse',text:'神像的面容早已模糊，掌心却仍握着一件闪烁的遗物。它等待的并非信仰，而是你愿意付出的代价。',choices:[['献上心血','失去 8 点生命，获得随机遗物。'],['静静祈祷','恢复 6 点生命。']]},
];
export function GameScenes({s,act,open,newRun}:{s:GameState;act:(a:Action)=>void;open:(name:string)=>void;newRun:()=>void}){
 return <>
 {s.phase==='map'&&<section className="adventure-screen map-screen"><MapView s={s} onNode={n=>act({type:'node',row:n.row,col:n.col})}/></section>}
 {s.phase==='reward'&&<section className="reward-overlay"><div className="reward-panel"><span className="eyebrow">ENCOUNTER CLEARED</span><div className="reward-symbol"><Swords size={33}/></div><h2>月光，为胜者加冕。</h2><p>选择一张卡牌，继续书写你的旅途。</p><div className="loot-row"><span><Coins size={17}/>{s.reward.gold} 金币 <Check size={13}/></span>{s.reward.relic&&<Tip title={RELICS[s.reward.relic].name} text={RELICS[s.reward.relic].desc}><span><Rune name={RELICS[s.reward.relic].icon} size={17}/>{RELICS[s.reward.relic].name}<Check size={13}/></span></Tip>}{s.reward.potion&&<span><FlaskConical size={16}/>{POTIONS[s.reward.potion].name}<Check size={13}/></span>}</div><div className="reward-cards">{s.reward.cards.map(owned=><CardView key={owned.uid} owned={owned} onClick={()=>act({type:'reward',uid:owned.uid})} preview/>)}</div><button className="text-button" onClick={()=>act({type:'reward',uid:null})}>跳过选牌 <ArrowRight size={16}/></button><small className="reward-hint">战利品已自动收取 · 精简牌组也是一种策略</small></div></section>}
 {s.phase==='camp'&&<section className="adventure-screen camp-screen"><div className="scene-heading"><span className="eyebrow">A MOMENT OF RESPITE</span><div className="large-rune warm"><Flame size={70} strokeWidth={1}/></div><h2>尚有余温。</h2><p>在漫长的黑夜里，允许自己停留片刻。</p></div><div className="choice-grid"><button className="choice-card" onClick={()=>act({type:'rest'})}><Heart size={30}/><h3>休憩</h3><p>恢复 <b>{Math.ceil(s.maxHp*.3)}</b> 点生命</p><small>当前生命 {s.hp} / {s.maxHp}</small><span>靠近营火 <ArrowRight size={16}/></span></button><button className="choice-card" disabled={!s.deck.some(x=>!x.up&&x.id!=='curse')} onClick={()=>open('upgrade')}><Swords size={30}/><h3>淬炼</h3><p>升级 <b>1</b> 张卡牌</p><small>锋刃终将回应你的意志</small><span>磨砺剑心 <ArrowRight size={16}/></span></button></div><p className="scene-footnote">只能选择一项，随后继续前进。</p></section>}
 {s.phase==='shop'&&<section className="adventure-screen shop-screen"><div className="shop-heading"><div><span className="eyebrow">THE MOONLIT EMPORIUM</span><h2>月下小铺</h2><p>“总有一件东西，是为你而来的。”</p></div><span className="shop-wallet"><Coins size={20}/>{s.gold}<small>金币</small></span></div><div className="shop-content"><div className="shop-cards">{s.shop.cards.map(owned=>{const sold=s.shop.sold.includes(String(owned.uid));return <div className="shop-item" key={owned.uid}><CardView owned={owned} onClick={()=>act({type:'buy',item:'card',uid:owned.uid})} disabled={sold||s.gold<cardPrice(owned.id)} preview/><span className={sold?'sold':''}>{sold?<><Check size={14}/>已购买</>:<><Coins size={15}/>{cardPrice(owned.id)}</>}</span></div>;})}</div><div className="shop-services">{s.shop.relic&&<button disabled={s.shop.sold.includes('relic')||s.gold<125} onClick={()=>act({type:'buy',item:'relic'})}><Rune name={RELICS[s.shop.relic].icon} size={31}/><div><h3>{RELICS[s.shop.relic].name}</h3><p>{RELICS[s.shop.relic].desc}</p></div><span>{s.shop.sold.includes('relic')?'已购买':<><Coins size={14}/>125</>}</span></button>}<button disabled={s.shop.sold.includes('potion')||s.gold<35||s.potions.length>=3} onClick={()=>act({type:'buy',item:'potion'})}><FlaskConical size={31}/><div><h3>月露药剂</h3><p>战斗中恢复 20 点生命。</p></div><span>{s.shop.sold.includes('potion')?'已购买':s.potions.length>=3?'药剂已满':<><Coins size={14}/>35</>}</span></button><button disabled={s.shop.sold.includes('remove')||s.gold<60||s.deck.length<=5} onClick={()=>open('remove')}><Trash2 size={29}/><div><h3>遗忘服务</h3><p>从牌组中永久移除一张牌。</p></div><span>{s.shop.sold.includes('remove')?'已使用':<><Coins size={14}/>60</>}</span></button></div></div><button className="primary-button shop-leave" onClick={()=>act({type:'leave'})}>告别店主 <ArrowRight size={16}/></button></section>}
 {s.phase==='event'&&<section className="adventure-screen event-screen"><div className="event-portrait"><img src="/assets/hero.png" alt="" aria-hidden="true"/><div className="event-seal"><Rune name={EVENTS[s.event].icon} size={64}/></div></div><div className="event-content"><span className="eyebrow">{EVENTS[s.event].kicker}</span><h2>{EVENTS[s.event].name}</h2><div className="title-rule">✧</div><p className="event-story">{s.eventResolved?s.eventText:EVENTS[s.event].text}</p>{s.eventResolved?<button className="primary-button" onClick={()=>act({type:'leave'})}>继续旅途 <ArrowRight size={17}/></button>:<div className="event-choices">{EVENTS[s.event].choices.map((choice,i)=>{const unavailable=(s.event===0&&i===1&&s.hp<=6)||(s.event===2&&i===0&&s.gold<25)||(s.event===3&&i===0&&s.hp<=8);return <button key={i} disabled={unavailable} onClick={()=>act({type:'event',choice:i})}><span className="choice-index">0{i+1}</span><div><h3>{choice[0]}</h3><p>{unavailable?'生命或金币不足':choice[1]}</p></div><ChevronRight size={21}/></button>;})}</div>}</div></section>}
 {s.phase==='chest'&&<section className="adventure-screen treasure-screen"><span className="eyebrow">A GIFT FROM THE PAST</span><div className="large-rune treasure"><Gift size={100} strokeWidth={1}/></div><h2>月封之匣</h2><p>它在这里等了很久。也许，它等的就是你。</p><button className="primary-button" onClick={()=>act({type:'chest'})}>解开封印 <Sparkles size={18}/></button><small>获得 1 件未拥有的随机遗物与 20 金币</small></section>}
 {(s.phase==='victory'||s.phase==='defeat')&&<section className={'adventure-screen ending-screen '+s.phase}><div className="ending-art"><img src="/assets/hero.png" alt="莉雅"/></div><div className="ending-content"><span className="eyebrow">{s.phase==='victory'?'A NEW DAWN':'UNTIL THE NEXT MOON'}</span>{s.phase==='victory'?<Sunrise size={54} strokeWidth={1}/>:<Moon size={54} strokeWidth={1}/>}<h2>{s.phase==='victory'?'长夜之后，仍有黎明。':'月光暂歇。'}</h2><p>{s.phase==='victory'?'你击碎了月蚀的诅咒。莉雅收起长剑，第一次看见了属于自己的日出。':'倒下的地方，并非故事的终点。下一次，让命运重新洗牌。'}</p><div className="run-stats">{[['抵达层数',Math.max(1,s.act*8+s.floor+1)],['战斗胜利',s.stats.battles],['打出卡牌',s.stats.cardsPlayed],['造成伤害',s.stats.damage]].map(([name,value])=><div key={name}><strong>{value}</strong><span>{name}</span></div>)}</div><div className="ending-relics">{s.relics.map(id=><Tip title={RELICS[id].name} text={RELICS[id].desc} key={id}><Rune name={RELICS[id].icon} size={23}/></Tip>)}</div><button className="primary-button" onClick={newRun}>再启旅途 <RotateCcw size={17}/></button><button className="text-button" onClick={()=>open('deck')}>回顾最终牌组 <Layers size={15}/></button></div></section>}
 </>;
}
